tr2:
  controller:
    state:
      type: joint_state_controller/JointStateController
      publish_rate: 50
    trajectory:
      ArmPosition:
        type: effort_controllers/JointTrajectoryController
        joints:
          - a0
          - a1
          - a2
          - a3
          - a4
        gains:
          a0: {p: 9.0, i: 10.0, d: 0.2, i_clamp: 1.0}
          a1: {p: 9.0, i: 10.0, d: 0.2, i_clamp: 1.0}
          a2: {p: 9.0, i: 10.0, d: 0.2, i_clamp: 1.0}
          a3: {p: 9.0, i: 10.0, d: 0.2, i_clamp: 1.0}
          a4: {p: 9.0, i: 10.0, d: 0.2, i_clamp: 1.0}
        constraints:
          goal_time: 10.0
          a0:
            goal: 0.1
          a1:
            goal: 0.1
          a2:
            goal: 0.1
          a3:
            goal: 0.1
          a4:
            goal: 0.1
    position:
      a0:
        type: effort_controllers/JointPositionController
        joint: a0
        pid: {p: 9.0, i: 10.0, d: 0.2, i_clamp: 1.0}
      a1:
        type: effort_controllers/JointPositionController
        joint: a1
        pid: {p: 9.0, i: 10.0, d: 0.2, i_clamp: 1.0}
      a2:
        type: effort_controllers/JointPositionController
        joint: a2
        pid: {p: 9.0, i: 10.0, d: 0.2, i_clamp: 1.0}
      a3:
        type: effort_controllers/JointPositionController
        joint: a3
        pid: {p: 9.0, i: 10.0, d: 0.2, i_clamp: 1.0}
      a4:
        type: effort_controllers/JointPositionController
        joint: a4
        pid: {p: 9.0, i: 10.0, d: 0.2, i_clamp: 1.0}
      h0:
        type: effort_controllers/JointPositionController
        joint: h0
        pid: {p: 9.0, i: 10.0, d: 0.2, i_clamp: 1.0}
      h1:
        type: effort_controllers/JointPositionController
        joint: h1
        pid: {p: 9.0, i: 10.0, d: 0.2, i_clamp: 1.0}
    effort:
      b0:
        type: effort_controllers/JointEffortController
        joint: b0
      a0:
        type: effort_controllers/JointEffortController
        joint: a0
      a1:
        type: effort_controllers/JointEffortController
        joint: a1
      a2:
        type: effort_controllers/JointEffortController
        joint: a2
      a3:
        type: effort_controllers/JointEffortController
        joint: a3
      a4:
        type: effort_controllers/JointEffortController
        joint: a4
      h0:
        type: effort_controllers/JointEffortController
        joint: h0
      h1:
        type: effort_controllers/JointEffortController
        joint: h1
