#tr2:
  joint_limits:

    a0:
      has_position_limits: true
      min_position: -1.5708
      max_position: 1.5708
      has_velocity_limits: true
      max_velocity: 0.25
      has_acceleration_limits: false
      max_acceleration: 0.0
      has_jerk_limits: true
      max_jerk: 100.0
      has_effort_limits: true
      max_effort: 1.0
      min_effort: -1.0

    a1:
      has_position_limits: true
      min_position: -3.1415
      max_position: 3.1415
      has_velocity_limits: true
      max_velocity: 0.25
      has_acceleration_limits: false
      max_acceleration: 0.0
      has_jerk_limits: true
      max_jerk: 100.0
      has_effort_limits: true
      max_effort: 1.0
      min_effort: -1.0

    a2:
      has_position_limits: true
      min_position: -3.1415
      max_position: 3.1415
      has_velocity_limits: true
      max_velocity: 0.25
      has_acceleration_limits: false
      max_acceleration: 0.0
      has_jerk_limits: true
      max_jerk: 100.0
      has_effort_limits: true
      max_effort: 1.0
      min_effort: -1.0

    a3:
      has_position_limits: true
      min_position: -3.1415
      max_position: 3.1415
      has_velocity_limits: true
      max_velocity: 0.25
      has_acceleration_limits: false
      max_acceleration: 0.0
      has_jerk_limits: true
      max_jerk: 100.0
      has_effort_limits: true
      max_effort: 1.0
      min_effort: -1.0

    a4:
      has_position_limits: true
      min_position: -3.1415
      max_position: 3.1415
      has_velocity_limits: true
      max_velocity: 0.25
      has_acceleration_limits: false
      max_acceleration: 0.0
      has_jerk_limits: true
      max_jerk: 100.0
      has_effort_limits: true
      max_effort: 1.0
      min_effort: -1.0
